# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - projectpilot

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
        inputs:
          environment:
            description: 'Deployment environment'
            required: true
            default: 'production'
          versionTag:
            description: 'Application version'
            required: false            
env:
  ARTIFACT_NAME: projectpilot-build-${{ github.event.inputs.versionTag || github.run_number }}-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: install module @rollup/rollup-linux-x64-gnu
        run: npm install @rollup/rollup-linux-x64-gnu

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME}}
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME}}
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_06FEFA3B1F344BE9A1566C1861B37731 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E1361E7ED40843A7B1A9B4E688A4C71C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1B3A432D354A422D9B8AD3C2FAADB533 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'projectpilot'
          slot-name: 'Production'
          package: .
          